/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        headline: ['"Climate Crisis"', 'cursive', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      colors: {
        stitch: {
          surface: '#f7f9fb',
          'surface-dim': '#d8dadc',
          'surface-bright': '#f7f9fb',
          'surface-lowest': '#ffffff',
          'surface-low': '#f2f4f6',
          'surface-container': '#eceef0',
          'surface-high': '#e6e8ea',
          'surface-highest': '#e0e3e5',
          'on-surface': '#191c1e',
          'on-surface-variant': '#45474c',
          outline: '#75777d',
          'outline-variant': '#c5c6cd',
          primary: '#435c5b',
          'primary-container': '#5b7573',
          'on-primary-container': '#defbf8',
          secondary: '#61611d',
          'secondary-container': '#e5e491',
          'on-secondary-container': '#656621',
          tertiary: '#006444',
          'tertiary-container': '#008058',
          'tertiary-fixed': '#6ffbbe',
          'tertiary-fixed-dim': '#4edea3',
          error: '#ba1a1a',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          navy: '#1e293b',
          blue: '#0058be',
        },
        primary: {
          50: '#f0fdf9',
          100: '#cce8e5',
          500: '#435c5b',
          600: '#354a49',
          700: '#273837',
          800: '#1e293b',
          900: '#0f172a',
        },
      },
    },
  },
  plugins: [],
};
